---
- name: Изменить приветствие системы (MOTD) с IP и именем хоста
  hosts: lecture_nodes
  become: yes
  tasks:
    - name: Записать приветствие с данными хоста
      copy:
        content: |
          ╔═══════════════════════════════════════════════╗
          ║  Привет, администратор! 👨‍💻                ║
          ║  Хост: {{ ansible_hostname }}                ║
          ║  IP:   {{ ansible_default_ipv4.address }}    ║
          ║                                               ║
          ║  Желаю продуктивного дня! ☀️                ║
          ╚═══════════════════════════════════════════════╝
          
        dest: /etc/motd
        mode: '0644'